### ISSUE TITLE
setup-media couldn't find informations from onepace.net

### ISSUE THREAD

**Issue by XRone99** [JakeLunn/one-pace-plex-assistant#11]
I'm sorry to disturb, I just would like to report that despite working well with previous arcs, now oppa is having issues to find informations about arabasta, wiskey peak and drum island

![image](https://github.com/JakeLunn/one-pace-plex-assistant/assets/81041677/3ba3f741-5937-4d9d-884b-c54393ab6373)

Thank you for your fine work!

**Comment by XRone99** [comment]
Could I suggest to use the episode code (like [3677DB27] for example) to identify episeodes instead of using the whole name
I think that One Pace community is starting to follow different standards in naming files
so maybe it could be easier for your program to get the string with the code and find it in the website
IDK just saying, I don't actually  undertand how all of this works
BTW thank you

**Comment by JakeLunn** [comment]
No worries! Thanks for reporting.

Just pushed a fix for some string formatting that wasn't getting applied and causing the mismatch error. Please let me know if [the latest version](https://github.com/JakeLunn/one-pace-plex-assistant/releases/tag/v0.1.7) resolves your issue.

As for the the episode code, I unfortunately could not find these codes anywhere in their API which means I can't use them to match episode files. My best guess is that these are some sort of version number indicator. It would be nice if the ID was in the filename or its metadata. That would make it much easier to match for sure.

**Comment by XRone99** [comment]
Thank you, I'm going to try it out now and let you know

**Comment by XRone99** [comment]
It seems like it's working pretty good!
