### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://onepace.net/_next/image?url=/images/episodes/cover-the-adventures-of-buggy's-crew-01.jpg&w=828&q=75

### ISSUE THREAD

**Issue by Lazycaker** [JakeLunn/one-pace-plex-assistant#13]
![image](https://github.com/JakeLunn/one-pace-plex-assistant/assets/148187865/a3b3261a-d6ad-4fcb-b95c-bca3c12eaf37)
Got this error during setup-media

**Comment by JakeLunn** [comment]
Hello, thanks for reporting this. The newest release should resolve the issue. 

[Download here](https://github.com/JakeLunn/one-pace-plex-assistant/releases/tag/v0.1.8)

Feel free to re-open if issue persists.
