### ISSUE TITLE
Episode title not showing in plex for Wano 33 - wano 38 and egghead 1 - egghead 2

### ISSUE THREAD

**Issue by Jov3nlzw** [JakeLunn/one-pace-plex-assistant#15]
Episode title not showing in plex for Wano 33 - wano 38 and egghead 1 - egghead 2

Every other episode title is working fine.
when running the comment this happens.

C:\Windows\System32>oppa setup-plex -t "vwoTmKbkFD2Cg_T4akMC" -ph "http://localhost:32400/web/" -l "Anime"  --one-piece-show-name "One Pace"
Traceback (most recent call last):
  File "main.py", line 97, in <module>
  File "main.py", line 90, in main
  File "modules\plex.py", line 55, in run
  File "plexapi\server.py", line 116, in __init__
  File "plexapi\server.py", line 764, in query
  File "xml\etree\ElementTree.py", line 1338, in XML
xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 2
[19468] Failed to execute script 'main' due to unhandled exception!

Please send help

**Comment by JakeLunn** [comment]
This implies an issue parsing the XML that's returned from your Plex server. I'm attempting to recreate it locally.

**Comment by Jov3nlzw** [comment]
> This implies an issue parsing the XML that's returned from your Plex server. I'm attempting to recreate it locally.

Yeap thx for looking into it, this took me so long to figure out how to use as i have 0 idea how all these works

**Comment by Jov3nlzw** [comment]
any updates?

**Comment by JakeLunn** [comment]
Apologies for not being timely with my responses, my full-time gig has been taking up a lot of my focus lately.

Can you please try the command again but this time remove the `/web/` in the -ph argument? So using the OP as the example, 
```cmd
C:\Windows\System32>oppa setup-plex -t "vwoTmKbkFD2Cg_T4akMC" -ph "http://localhost:32400" -l "Anime" --one-piece-show-name "One Pace"
```

#16  Fixes an error in the Readme which erroneously suggested to add the /web/ for the plex host. 

If that doesn't resolve the issue, feel free to update here. Cheers.

**Comment by Jov3nlzw** [comment]
Oh wow it did fix the issue
u are a god send thank you :)
