### ISSUE TITLE
Directory locations using quotes (because of whitespace character) don't work

### ISSUE THREAD

**Issue by Breadleyg** [JakeLunn/one-pace-plex-assistant#4]
Looks like the following does not work:

```
PS Z:\> oppa setup-media --source-dir 'Z:\Downloads\media\series\One Pace\' --target-dir 'Z:\Downloads\media\series\One Piece\'
usage: onepace-plex-importer setup-media [-h] --source-dir SOURCE_DIR --target-dir TARGET_DIR
onepace-plex-importer setup-media: error: the following arguments are required: --target-dir
```

After changing the names of the folders to not contain whitespace the program didn't throw the missing arguments exception

**Comment by JakeLunn** [comment]
Thanks for reporting this. This appears to be a bug with Windows Powershell ([see the article here](https://stackoverflow.com/questions/75527560/python-argparse-not-working-corrrectly-with-path-in-windows)) in versions pre-7. 

As a workaround, you can try adding an `\` to the closing of your path arguments like so:
```powershell
oppa setup-media --source-dir 'Z:\Downloads\media\series\One Pace\\' --target-dir 'Z:\Downloads\media\series\One Piece\\'
```
This worked for me when testing locally.

Alternatively, updating your PowerShell version to Core 7.0+ should also correct the problem (I haven't tested this personally, but the article says so).

**Comment by JakeLunn** [comment]
I tested on PowerShell Core 7 and verified that it works as expected.
