### ISSUE TITLE
Failed to execute script 'main' due to unhandled exception!

### ISSUE THREAD

**Issue by XRone99** [JakeLunn/one-pace-plex-assistant#7]
I was following the instructions but when i try to use the function to relocate files this happens: 
![image](https://github.com/JakeLunn/one-pace-plex-assistant/assets/81041677/e01c0162-beb3-4aef-900c-8518094b3c7d)

**Comment by JakeLunn** [comment]
It looks like it failed to extract the Episode # from the name of the file it was processing.

Can you please [try the latest version here](https://github.com/JakeLunn/one-pace-plex-assistant/releases/tag/v0.1.5)?

If it fails again, it should at least have a better error message than in the screenshot above. The file-matching was also updated to account for spaces in the file name a little bit better, in-case that was the issue.

I would also make sure that the file names are unmodified from when they were downloaded from onepace.net. If they are unmodified, then there's likely a weird difference in the name that needs to be accounted for.

**Comment by XRone99** [comment]
Yeah it is working perfectly now 
(It is not recognizing "[One Pace][83-119] The Trials of Koby-Meppo [1080p][4B56844F]" but i think it is accountable to onepace.net names or somethink)

Everything else seems to work fine

**Comment by JakeLunn** [comment]
Ah that makes sense, no episode # in the file name. I've just [released a fix for this here](https://github.com/JakeLunn/one-pace-plex-assistant/releases/tag/v0.1.6) which will assume 01 if no episode # is found. I tested it on Koby-Meppo.

Going to close this as resolved for now - feel free to re-open if v0.1.6 does not resolve the issue. Thanks for reporting!

**Comment by XRone99** [comment]
Thnak you very much!
